[11/19 | 02:07:53] [ERROR] Task was destroyed but it is pending!
task: <Task pending coro=<_run_event() running at C:\Users\Vicente\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py:307> wait_for=<Future pending cb=[Task._wakeup()]>>
